sudo: required
language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "pypy"
before_install:
  - scripts/install-apache-mod-wsgi
install:
  - pip install coveralls
  - LC_ALL=C pip install .
script:
  - make check
  - scripts/collect-full-coverage
after_success:
  - coveralls
