sudo: required
language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
before_install:
  - scripts/install-on-travis.sh
install:
  - pip install pip-accel
  - pip-accel install coveralls
  - pip-accel install --requirement=requirements.txt
  - pip-accel install --requirement=requirements-checks.txt
  - pip-accel install --requirement=requirements-tests.txt
  - LC_ALL=C pip-accel install .
script:
  - make check
  - make full-coverage
after_success:
  - coveralls
branches:
  except:
    - /^[0-9]/
